src/accounts/urls.py
from django.conf.urls import patterns, include, url

from . import views

urlpatterns = patterns(
    '',
    url(r'^login/$', views.LoginView.as_view(), name="login"),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.SignUpView.as_view(), name='signup'),
    url(r'^password-change/$', views.PasswordChangeView.as_view(),
        name='password-change'),
    url(r'^password-reset/$', views.PasswordResetView.as_view(),
        name='password-reset'),
    url(r'^password-reset-done/$', views.PasswordResetDoneView.as_view(),
        name='password-reset-done'),
    url(r'^password-reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$$', views.PasswordResetConfirmView.as_view(),
        name='password-reset-confirm'),
)

src/my_proj/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
import profiles.urls
import accounts.urls
from . import views
from profiles.models import *

urlpatterns = patterns(
    '',
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^about/$', views.AboutPage.as_view(), name='about'),
    url(r'^', include(accounts.urls, namespace='accounts')),
    url(r'^users/', include(profiles.urls, namespace='profiles')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^create/', views.StartUpCreate.as_view(success_url="/"), name='create'),
    url(r'^browse/sort/name/', views.NameBrowsePage.as_view(), name='sorted_by_name'),
    url(r'^browse/sort/date/', views.DateBrowsePage.as_view(), name='sorted_by_date'),
    url(r'^browse/', views.BrowsePage.as_view(), name='browse'),
    url(r'^category/(?P<category_id>\d+)?/?$', views.CategoryListView.as_view(), name='category'),
    url(r'^tag/(?P<slug>[-\w]+)/$', views.TagIndexView.as_view(), name='tags'),
    url(r'^my_startups/', views.UserListings.as_view(), name='my_startups'),
    url(r'^detail/(?P<pk>\d+)?/?$', views.StartUpDetail.as_view()),
    url(r'^edit_startup/(?P<pk>\d+)?/?$', views.UpdateStartup.as_view()),
    url(r'^delete_startup/(?P<pk>\d+)?/?$', views.DeleteStartup.as_view()),
    url(r'^like_startup/(?P<startup_id>\d+)?/?$', views.like_startup, name='like_startup'),
    url(r'^dislike_startup/(?P<startup_id>\d+)?/?$', views.dislike_startup, name='dislike_startup'),
    url(r'^json_list/(?P<k>[0-9]+)/(?P<date1>\d{4}-\d{2}-\d{2})/(?P<date2>\d{4}-\d{2}-\d{2})/$', views.json_list),
    url(r'^charts/$', views.line_chart, name='chart'),
    url(r'^chart_json/$', views.line_chart_json, name='line_chart_json'),
)

# User-uploaded files like profile pics need to be served in development
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/profiles/urls.py
from django.conf.urls import patterns, include, url
from . import views

urlpatterns = patterns(
    '',
    url(r'^me$', views.ShowProfile.as_view(), name='show_self'),
    url(r'^me/edit$', views.EditProfile.as_view(), name='edit_self'),
    url(r'^(?P<slug>\w+)$', views.ShowProfile.as_view(),
        name='show'),
)

src/profiles/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
import uuid
from django.db import models
from django.conf import settings

from taggit.managers import TaggableManager

class BaseProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                primary_key=True)
    slug = models.SlugField(max_length=32, unique=True, blank=True,
                            editable=False)
    # Add more user profile fields here. Make sure they are nullable
    # or with default values
    name = models.CharField(max_length = 20,null=True, blank=True)
    picture = models.ImageField('Profile picture',
                                upload_to='profile_pics/%Y-%m-%d/',
                                null=True,
                                blank=True)
    bio = models.CharField("Short Bio", max_length=200, blank=True, null=True)
    email_verified = models.BooleanField("Email verified", default=False)

    def save(self, *args, **kwargs):
        if self.slug is None or len(self.slug) == 0:
            self.slug = uuid.uuid4().hex
        super(BaseProfile, self).save(*args, **kwargs)

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Profile(BaseProfile):
    def __str__(self):
        return "{}'s profile". format(self.user)
        
class Category(models.Model):
    name = models.CharField(max_length=200, unique=True)
    description = models.TextField()
    
    def __str__(self):
        return self.name
    

class StartUpIdea(models.Model):
    creator = models.ForeignKey(Profile)
    name = models.CharField(max_length=20)
    pub_date = models.DateField(auto_now=True)
    description = models.TextField()
    likes = models.IntegerField(default=0)
    category = models.ForeignKey(Category)
    tags = TaggableManager()
    
    def __str__(self):
        return self.name
    

src/templates/_brandname.html
My_Proj

src/templates/_navbar.html
<li {% if active_link == "home" %}class="active"{% endif %}><a href="{% url 'home' %}">Home</a></li>
<li {% if active_link == "browse" %}class="active"{% endif %}><a href="{% url 'browse' %}">Browse</a></li>
<li {% if active_link == "create" %}class="active"{% endif %}><a href="{% url 'create' %}">Create</a></li>

src/templates/about.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}

<div id="sec1" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h1>{% include "_brandname.html" %}</h1>
        <p class="lead">An Awesome Tagline Goes Here</p>
      </div>
    </div>
  </div>
</div>

<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
      <div class="col-md-12 text-center">
        <h2>Meet The Team</h2>
        <p class="lead">The Wonderful People Behind the Site</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/9/" alt="profile pic"></div>
        <p class="heavy text-center">Cassidy Coder</p>
        <h2>Front-end developer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/2/" alt="profile pic"></div>
        <p class="heavy text-center">James King</p>
        <h2>CEO</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
      <div class="col-lg-4">
        <div class="text-center"><img class="img-circle centered" src="http://lorempixel.com/128/128/people/1/" alt="profile pic"></div>
        <p class="heavy text-center">Kate Lamport</p>
        <h2>Front-end designer</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      </div>
    </div>
    </div>
  </div>
</div>

<div id="sec3">
  <div class="container">
    <div class="row">
      <div id="map-outer" class="col-md-12">
        <div id="address" class="col-md-4">
          <h2>Our Location</h2>
          <address>
            <strong>Edge Solutions Ltd.</strong><br>
            Taj Mahal<br>
            Agra<br>
            Uttar Pradesh<br>
            India - 282001<br>
            <abbr>P:</abbr> +91 0562 222 6431
          </address>
        </div>
        <div id="map-container" class="col-md-8"></div>
      </div>
    </div>
  </div>
</div>
{% endblock container %}

{% block scripts %}
  <script src="http://maps.google.com/maps/api/js?sensor=false"></script>
  <script>

   function init_map() {
     // Enter the latitude and longitude of your office here
	 var myLocation = new google.maps.LatLng(27.176141, 78.042370);

     var mapOptions = {
          center: myLocation,
          zoom: 14
     };

	 var marker = new google.maps.Marker({
	   position: myLocation,
	   title:"We are here"});

     var map = new google.maps.Map(document.getElementById("map-container"),
                                   mapOptions);
	 marker.setMap(map);
   }

   google.maps.event.addDomListener(window, 'load', init_map);
  </script>
{% endblock scripts %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load staticfiles %}
    {% load thumbnail %}
    
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block description %}{% endblock description %}">
    <meta name="author" content="Arun Ravindran">
    <link rel="shortcut icon" href="{% static 'site/ico/favicon.ico' %}">

    <title>{% block title %}{% include "_brandname.html" %} :: {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this site -->
    {% block styles %}
    <link href="{% static 'site/css/main.css' %}" rel="stylesheet">
    {% endblock styles %}

    <!-- Custom tags for the head tag -->
    {% block extrahead %}{% endblock extrahead %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    {% block navbar %}
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'home' %}">
            {% block navbar-brand %}
              <img src="{% static 'site/img/logo.png' %}" alt="logo">
              {% include "_brandname.html" %}
            {% endblock %}
          </a>
        </div>
        {% block navbar-menu %}
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block navbar-left %}{% endblock %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% block navbar-right %}
              {% if user.is_authenticated %}
                {% if user.is_staff %}
                <li><a href="{% url 'admin:index' %}">Admin</a></li>
                {% endif %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle profile-menu" data-toggle="dropdown">
			<img src="{% thumbnail user.profile.picture|default:'default_profile.png' 30x30 crop %}" alt="" />
			{{ user.get_full_name|truncatechars:20 }}
			<span class="caret"></span>
		    </a>
		    
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="{% url 'profiles:show_self' %}">Profile</a></li>
                    <li><a href="{% url 'my_startups' %}">My Startups</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>

                  </ul>
                </li>
              {% endif %}
            {% endblock %}
          </ul>
          </ul>
        </div><!--/.nav-collapse -->
        {% endblock %}
    </div>
    {% endblock navbar %}

    {% block messages %}
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-{{ message.tags }}">  <!-- singular -->
            <a class="close" data-dismiss="alert">×</a>
            {{ message|safe }}
          </div>
        {% endfor %}
      {% endif %}
    {% endblock %}

    {% block splash %}
    {% endblock splash %}
    
    {% block container %}
    <div class="container">

      <div class="starter-template">
        <h1>New Project</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </div><!-- /.container -->
    {% endblock container %}

    <!-- Site footer -->
    {% block footer %}
      <!-- Some social button for contact will do -->
      <a name="contact"></a>
      <div class="container">
            <div class="footer">
        <div class="row">
          <div class="col-lg-6">
              <p>&copy; Company {% now 'Y' %}</p>
          </div>
          <div class="col-lg-6 text-right">
            Connect with us on
            <a href="#"><i class="fa fa-facebook"></i> Facebook</a> or
            <a href="#"><i class="fa fa-twitter"></i> Twitter</a>
          </div>
        </div>
            </div>
      </div>
    {% endblock %}

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'site/js/rango-ajax.js' %}"></script>
    {% block scripts %}
    {% endblock scripts %}
  </body>
</html>

src/templates/browse.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}
<div id="sec2" class="text-page">
  <div class="container">
<h1>Start-up Ideas</h1>
<ul>
{% for idea in object_list %}
    <li><a href="/detail/{{ idea.id }}">{{ idea.name }} - {{ idea.pub_date|date }}
    {% if idea.category %}
        <div class="col-md-12">
        <a href="/category/{{ idea.category.id }}"><span class="label label-primary">{{ idea.category.name }}</span></a>
        </div>
    {% endif %}
    {% if idea.tags %}
        <div class="col-md-12">
        {% for tag in idea.tags.all %}
        <a href="/tag/{{ tag.slug }}"><span class="label label-success">{{ tag.name }}</span></a>
        {% endfor %}
        </div>
        {% endif %}
    </li></a>
{% empty %}
    <li>No articles yet.</li>
{% endfor %}
</ul>
  </div>
</div>
{% endblock %}

src/templates/create_startup.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Create Startup{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}


{% block container %}
<div id="sec2" class="text-page">
  <div class="container">
      <div class="post col-md-12">

<form action="" method="post">
{% csrf_token %}
{{ form.non_field_errors }}

<p><input type="hidden" id="id_creator" name="creator" value="{{ user.id }}"></p>

{{ form.name.errors }}
    <label for="{{ form.name.id_name }}">Startup Name:</label>
    <div class="input-group">{{form.name}}</div>
{{ form.description.errors }}
    <label for="{{ form.description.id_description }}">Description:</label>
    <div class="input-group">{{form.description}}</div>
{{ form.category.errors }}
    <label for="{{ form.category.id_category }}">Category:</label>
    <div>{{form.category}}</div>
{{ form.tags.errors }}
    <label for="{{ form.tags.id_tags }}">Tags:</label>
    <div class="input-group">{{form.tags}}</div>
<input type="submit" value="Submit" />
</form>

        </div>
    </div>
</div>

{% endblock %}

src/templates/delete_startup_confirm.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

src/templates/home.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}Home{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="home" %}
{% endblock %}

{% block navbar-right %}
  {% if not user.is_authenticated %}
<a class="btn btn-default" href="{% url 'accounts:login' %}" role="button">Log in</a>
<a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up</a>
  {% else %}
    {{ block.super }}
  {% endif %}
{% endblock %}

{% block splash %}
  <div class="jumbotron jumbotron-carousel corporate-jumbo">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-sm-8">
          <h1>{% include "_brandname.html" %}</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
	  <a class="btn btn-primary" href="{% url 'accounts:signup' %}" role="button">Sign up for Free!</a>
        </div>
        <div class="col-md-4 col-sm-4">

        </div>
      </div>
    </div>
  </div>
{% endblock splash %}

{% block container %}
<!-- Benefits of the Django application -->
<a name="about"></a>

<div class="container">
  <div class="row">
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
    <div class="col-lg-4">
      <h2>Heading</h2>
      <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
      <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

{% endblock container %}

{% block scripts %}
<script src="{% static 'site/js/site.js' %}"></script>
{% endblock scripts %}

src/templates/line_chart.html
{% load staticfiles %}
<html>
    <head>
        <title>django-chartjs line chart demo</title>
        <!--[if lte IE 8]>
            <script src="{% static 'js/excanvas.js' %}"></script>
        <![endif]-->
    </head>
    <body>
        <h1>Some Line Charts loaded in Ajax!</h1>

        <canvas id="myChart" width="500" height="400"></canvas>

        <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
        <script type="text/javascript" src="{% static 'site/js/Chart.min.js' %}"></script>
        <script type="text/javascript">
            $.get('{% url "line_chart_json" %}', function(data) {
                var ctx = $("#myChart").get(0).getContext("2d");
                new Chart(ctx).Bar(data);
            });
        </script>
    </body>
</html>

src/templates/line_chart2.html
{% load staticfiles %}
<html>
 <head>
 <script type="text/javascript" src="http://code.jquery.com/jquery-1.10.0.min.js"></script>
 <script type="text/javascript" src="{% static 'site/js/highcharts.js' %}"></script>
 <strong>{% load chartit %}</strong>
 <strong>{{ weatherchart|load_charts:”container” }}</strong>
 </head>
 <body>
 <div id=”container”>
 </div>
 </body>
 </html>

src/templates/main_browse.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}
<div id="sec2" class="text-page">
  <div class="container">
<h1>Start-up Ideas</h1>
<h3>Order by: <a href="/browse/sort/pub_date/">Date</a>      <a href="/browse/sort/name/">Name</h3>
<ul>
{% for idea in object_list %}
    <li><a href="/detail/{{ idea.id }}">{{ idea.name }} - {{ idea.pub_date|date }}
    {% if idea.category %}
        <div class="col-md-12">
        <a href="/category/{{ idea.category.id }}"><span class="label label-primary">{{ idea.category.name }}</span></a>
        </div>
    {% endif %}
    {% if idea.tags %}
        <div class="col-md-12">
        {% for tag in idea.tags.all %}
        <a href="/tag/{{ tag.slug }}"><span class="label label-success">{{ tag.name }}</span></a>
        {% endfor %}
        </div>
        {% endif %}
    </li></a>
{% empty %}
    <li>No articles yet.</li>
{% endfor %}
</ul>
  </div>
</div>
{% endblock %}

src/templates/startup_detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}


{% block container %}
<div id="sec2" class="text-page">
  <div class="container">
    <div class="row">
<div class="col-md-12 text-center">
<h1>{{ object.name }}</h1>
<h3>{{ object.creator.user.name }}</h3>
<h4>{{ object.pub_date }}</h4>
<div class="text-center">

<div class="panel panel-default">
  <div class="panel-body">
    <p>{{ object.description }}</p>
  </div>
</div>


</div>
</div>
{% if object.category %}
<div class="col-md-12">
<a href="/category/{{ object.category.id }}"><span class="label label-primary">{{ object.category.name }}</span></a>
</div>
{% endif %}
{% if object.tags %}
<div class="col-md-12">
{% for tag in object.tags.all %}
<a href="/tag/{{ tag.slug }}"><span class="label label-success">{{ tag.name }}</span></a>
{% endfor %}
</div>
{% endif %}
</div>
<div class="row">
  <div class="row">
  </div>
</div>  
<div class="row">

 <div class="col-md-12">
<b id="like_count">{{ object.likes }}</b> people like this Idea
<br />
{% if user.is_authenticated %}
        <a href="/like_startup/{{ object.id }}"><button id ="likes" data-catid="{{object.id}}" class="btn btn-mini btn-primary" type="button">Like</button></a>
        <a href="/dislike_startup/{{ object.id }}"><button id ="likes" data-catid="{{object.id}}" class="btn btn-mini btn-primary" type="button">Dislike</button></a>
{% endif %}
</div>

</div>
</div>
  </div>
</div>



{% endblock %}

src/templates/update_startup.html
<form action="" method="post">
{% csrf_token %}
<p><input type="hidden" id="id_creator" name="creator" value="{{ user.id }}"></p>
<div>{{form.name}}</div>
<div>{{form.description}}</div>
<div>{{form.category}}</div>
<div>{{form.tags}}</div>
<input type="submit" value="Submit" />
</form>

src/templates/user_listings.html
{% extends "base.html" %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}{{ block.super }}About{% endblock %}

{% block navbar-left %}
  {% include "_navbar.html" with active_link="about" %}
{% endblock %}

<!-- Benefits of the Django application -->
{% block container %}
<div id="sec2" class="text-page">
  <div class="container">
<h1>Your Listings</h1>
<ul>
{% for idea in object_list %}
{% if idea.creator.user.id == user.id %}
    <li><a href="/detail/{{ idea.id }}">{{ idea.pub_date|date }} - {{ idea.name }}</li></a>
    <a href="/edit_startup/{{ idea.id }}"><button id ="edit" data-catid="{{idea.id}}" class="btn btn-mini btn-primary" type="button">Edit</button></a><a href="/delete_startup/{{ idea.id }}"><button id ="delete" data-catid="{{idea.id}}" class="btn btn-mini btn-primary" type="button">Delete</button></a>
{% endif %}
{% empty %}
    <li>No articles yet.</li>
{% endfor %}
</ul>
  </div>
</div>

{% endblock %}